#!/usr/bin/env python3

"""Garnet ingest cache daemon.

Extracts agent data from cache directory files.

"""

# Standard libraries
import sys
import time


# Garnet libraries
try:
    from garnet.cli import CLI
except:
    print('You need to set your PYTHONPATH to include the Garnet library')
    sys.exit(2)

def main():
    """Process agent data.

    Args:
        None

    Returns:
        None

    """
    # Get configuration
    cli = CLI()

    # Do control
    cli.control()


if __name__ == "__main__":
    main()
